#
# Configuration file for Travis CI
# https://travis-ci.org
#

language: java

os: linux

dist: bionic

jdk:
  - openjdk8
  - openjdk11
  - openjdk15

addons:
  apt:
    packages:
      - xvfb

before_install:
  - export DISPLAY=':10.0'
  - Xvfb :10 -screen 0 1024x768x24 > /dev/null 2>&1 &

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=false -B -V


